#!/bin/sh
# hyprctl activewindow -j | jq --raw-output .title
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{print $3}' | stdbuf -o0 awk '{ if (length($0) > 80) print substr($0, 1, 80)"..."; else print $0 }'
