# preload = ~/Pictures/yosemite.jpg
# preload = ~/Pictures/abstract.png
# preload = ~/Pictures/arch_wallpaper_1.png
# preload = ~/Pictures/arch_wallpaper_2.png
# preload = ~/Pictures/penrose3.png
# preload = ~/Pictures/piltover2.jpg
# wallpaper = , ~/Pictures/penrose3.png
preload = ~/Downloads/E07-68.png
preload = ~/Downloads/119.png
# wallpaper = , ~/Downloads/E07-68.png
wallpaper = , ~/Downloads/119.png

# wallpaper = , ~/Pictures/abstract.png
